version: "3.8"
services:
  elm-project:
    # Dockerfileビルド
    build: ./node
    # ディレクトリを共有する。
    volumes:
      - ../src:/app/src
      - ../elm.json:/app/elm.json
      - ../public:/app/public
      # elm packageのキャッシュ
      - cacheGardenElmStuffStarter:/app/elm-stuff
      - cacheGardenDotElmStarter:/root/.elm
    ports:
      - 8000:8000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。
    working_dir: /app
    command: [npx, elm-live, src/Main.elm, -h, '0.0.0.0', -H]

volumes:
  # elmのpackageを毎回ダウンロードしなくてもよいように、キャッシュを行う。2か所のキャッシュが必要。
  cacheGardenElmStuffStarter:
  cacheGardenDotElmStarter:
