version: "3.8"
services:
  elm_pages:
    # Dockerfileビルド
    build: .
    # ディレクトリを共有する。
    volumes:
      - ./src:/app/src
      - ./images:/app/images
      - ./content:/app/content
      - ./elm.json:/app/elm.json
      - ./elm-tooling.json:/app/elm-tooling.json
      - ./index.js:/app/index.js
      - ./style.css:/app/style.css
      - ../public:/app/dist
      # elm packageのキャッシュ
      - cacheGardenElmStuffStarter:/app/elm-stuff
      - cacheGardenDotElmStarter:/root/.elm
    ports:
      - 3000:3000
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # デフォルトの設定の場合、vagrantだとファイルの変更を検知できない。pollingが必要。
    working_dir: /app
    command: [npm, start]
volumes:
  # elmのpackageを毎回ダウンロードしなくてもよいように、キャッシュを行う。2か所のキャッシュが必要。
  cacheGardenElmStuffStarter:
  cacheGardenDotElmStarter:
